server:
  host: localhost
  port: "8081"
database:
  userName: "root"
  password: "1234@123"
  host: "127.0.0.1"
  port: "3306"
  dbName: "taskDB"
rabbitMQ:
  host: "localhost"
  pass: "guest"
  port: "5672"
  user: "guest"
  vHost: ""
userService:
  getUser: "http://localhost:8080/user/get"